version: '3.4'

services:

  module-second:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - APP_PORT=8878
    ports:
      - 8878:8878
    volumes:
      - ./src:/usr/src1/module-second