version: '3.4'

services:

  module-first:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - APP_PORT=3000
    ports:
      - 8877:8877
    volumes:
      - ./src:/usr/src/module-first