version: '3.4'

services:
  main-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./main-backend/.env
    environment:
      - APP_PORT=3000
    ports:
      - 3000:3000

  module-first:
    build:
      context: .
      dockerfile: Dockerfile.module1
    env_file: ./module-first/.env
    environment:
      - APP_PORT=3001
    ports:
      - 3001:3001

  module-second:
    build:
      context: .
      dockerfile: Dockerfile.module2
    env_file: ./module-second/.env
    environment:
      - APP_PORT=3002
    ports:
      - 3002:3002