FROM node:18-alpine as builder

# Create app directory
ENV HOME=/nestjs-microservices/module-second
WORKDIR ${HOME}

# Copy contents from the main-backend directory to /usr/src/app
COPY module-second/package.json module-second/yarn.lock ./

RUN yarn

COPY module-second/ .

EXPOSE 3002

CMD ["yarn", "start"]